api:
  dashboard: true
  insecure: true

ping: {}

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8082"
  postgres:
    address: ":5432"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
